version: "3.1"

services:
  app:
    build: .
    container_name: clean-arch-rust
    command: .docker/start.sh
    volumes:
      - .:/home/rust/app
    ports:
      - 8888:8888

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
